### ISSUE TITLE
folderlisted event enhancements

### ISSUE THREAD

**Issue by mfrisbey** [adobe/node-smb-server#20]
It would help improve performance in clients if the SMB server included the contents of the listed folder when it emits the folderlisted event. This way the client doesn't need to submit another request to list the contents of the same directory.

I propose adding the list of folders/files in a directory as data on the folderlisted event.

**Comment by stefan-guggisberg** [comment]
i noticed that the `'folderListed'` event emitted by the `SMBServer` object has been replaced by a `'folderlisted'` (note different case) emitted by SPI `Tree` and `Share`, with different signature and payload. 

since the new event is only emitted by a specific SPI implementation (supporting a specific use case) i suggest to either support and document it for all existing SPI implementations or at least restore the original `'folderListed'` event on `SMBServer` (where it is also documented as part of the `SMBServer` contract).

**Comment by mfrisbey** [comment]
@stefan-guggisberg: good call on all accounts. I've submitted another pull request that reverts the removal of the `folderListed` event and changed the name of the SPI-specific event. Please see #24

**Comment by stefan-guggisberg** [comment]
thanks, mark!
