### ISSUE TITLE
Will Windows support be soon?

### ISSUE THREAD

**Issue by davidaq** [adobe/node-smb-server#6]
I tried out this project using windows (Win10) as client. I managed to pass the authentication by turning off `extendedSecurity`. But then after login windows immediatly alerts that I can't use the share maybe because I don't have privilege.

**Comment by Freundschaft** [comment]
how did you manage to connect via windows? isnt samba running all the time on windows? how do you override the port used?

**Comment by stefan-guggisberg** [comment]
sorry, i won't have time to debug and work on windows client support in the near future but i'd be happy to accept pull requests.

**Comment by brandonros** [comment]
Windows 7: `error: [SMB] unsupported NetBIOS session service message type: 79` during authenticating, even if you change `extendedSecurity` to `false` in `config.json`.

**Comment by brandonros** [comment]
@Freundschaft Pass this into `Map network drive`: `\\localhost:8445\fs`

**Comment by matianfu** [comment]
@brandonros `error: [SMB] unsupported NetBIOS session service message type: 79` is because windows explorer treat `\\x.x.x.x:8445\fs` as webdav server, not smb server. Change port 8445 to 445 and start server as super user (`sudo npm start`) will pass that error. But there are other errors preventing windows client from functioning properly.

It seems that smb protocol consists of a large set of commands. Mac client uses a subset of them. and windows client uses some commands that is not supported by this project, yet.

**Comment by matianfu** [comment]
@stefan-guggisberg 

can you provide the smb protocol specifications in developer documents? Lots of people are interested in this project and I am sure many of them wish to contribute pull requests. Samba has been the only practical smb server choice on platform other than windows for many years. It is hard to integrate and customize. It is the time to change the situation. Also, thank you for your hard working and excellent job.

**Comment by stefan-guggisberg** [comment]
@matianfu 

thanks, appreciated. currently supported are the CIFS and MS-SMB 1.0 protocol. SMB2 support is incomplete and at an early stage.

the specifications can be found here:

-  [MS-CIFS](https://msdn.microsoft.com/en-us/library/ee442092.aspx)
-  [MS-SMB](https://msdn.microsoft.com/en-us/library/cc246231.aspx)
-  [MS-SMB2](https://msdn.microsoft.com/en-us/library/cc246482.aspx)

currently the only supported client is os-x Finder (due to our internal project's requirements).  supporting other clients will require analysing the wire conversation. i've used wirkeshark.
